### ISSUE TITLE
Better error messages when modules don't installed

### ISSUE THREAD

**Issue by bbultman** [siddharthkp/auto-install#12]
Might be a nice idea to not hide the error messages if a module can't be installed. Would prevent the user from having to install the package manually just to get some useful info. Should also be relatively simple to implement. Thoughts?

For example: 

version 1.2.4 crashes when trying to request something without a network connection - I guess when it tries to verify if it's a trusted package or not.

``` sh
/Users/bananas/.nvm/versions/node/v6.2.2/lib/node_modules/auto-install/node_modules/sync-request/index.js:37
    throw new Error(response.error.message || response.error || response);
    ^

Error: getaddrinfo ENOTFOUND api.npmjs.org api.npmjs.org:443
    at doRequest (/Users/bananas/.nvm/versions/node/v6.2.2/lib/node_modules/auto-install/node_modules/sync-request/index.js:37:11)
    at isModulePopular (/Users/bananas/.nvm/versions/node/v6.2.2/lib/node_modules/auto-install/helpers.js:187:18)
    at Object.installModule (/Users/bananas/.nvm/versions/node/v6.2.2/lib/node_modules/auto-install/helpers.js:47:24)
    at FSWatcher.main (/Users/bananas/.nvm/versions/node/v6.2.2/lib/node_modules/auto-install/index.js:25:66)
    at emitOne (events.js:96:13)
    at FSWatcher.emit (events.js:188:7)
    at FSWatcher.<anonymous> (/Users/bananas/.nvm/versions/node/v6.2.2/lib/node_modules/auto-install/node_modules/chokidar/index.js:191:15)
    at FSWatcher._emit (/Users/bananas/.nvm/versions/node/v6.2.2/lib/node_modules/auto-install/node_modules/chokidar/index.js:233:5)
    at FSWatcher.<anonymous> (/Users/bananas/.nvm/versions/node/v6.2.2/lib/node_modules/auto-install/node_modules/chokidar/lib/fsevents-handler.js:204:14)
    at addOrChange (/Users/bananas/.nvm/versions/node/v6.2.2/lib/node_modules/auto-install/node_modules/chokidar/lib/fsevents-handler.js:210:7)
```

I'm guessing there are situations when npm will fail even with a connection, though I haven't tested that theory.

**Comment by siddharthkp** [comment]
Ouch, that's horrible! 

There are two parts to what you said - 

> Might be a nice idea to not hide the error messages if a module can't be installed.

Agreed, I hope I can add some nice error messages here instead of the call stack

> crashes when trying to request something without a network connection

That's just bad error handling, will fix it

P.S. nice user name :wink:

> /Users/bananas/

**Comment by siddharthkp** [comment]
@bbultman,

> Might be a nice idea to not hide the error messages if a module can't be installed.

Fixed this part in https://github.com/siddharthkp/auto-install/pull/16

Moved the second part to https://github.com/siddharthkp/auto-install/issues/17

**Comment by siddharthkp** [comment]
@bbultman Fixed internet issues in https://github.com/siddharthkp/auto-install/pull/23
