### ISSUE TITLE
Does not work with node < 6.x

### ISSUE THREAD

**Issue by rjrahul** [siddharthkp/auto-install#31]
Release 1.3.10 does not work with node < 6.x. Following error comes when starting `auto-install` in a folder

```
/Users/XX/.npm/lib/node_modules/auto-install/index.js:8
let watchersInitialized = false;
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3
```

**Comment by siddharthkp** [comment]
@rjrahul Sorry, this took forever!

Had to write some test and make they run across node versions first.
