### ISSUE TITLE
Crashes when there are syntax errors in the file

### ISSUE THREAD

**Issue by zeg-io** [siddharthkp/auto-install#37]
I'm running the version I submitted a pull request for (which is why I can install @scoped modules)  It was running fine and then unexpectedly crashed.  I can't really tell you why, I just looked over and it had crashed.  I was able to restart it afterwards just fine.

```
$ auto-install
✖ debug removed
✖ jade removed
✖ tedious removed
✔ mongodb installed
Watchers initialized
✔ @zetta/sql-boilerplate installed
✖ @zetta/log-colors removed
✖ mssql removed
✖ mongodb removed
✖ mongoose removed
✔ @zetta/mongo-ore-boilerplate installed
/usr/local/lib/node_modules/auto-install/node_modules/acorn/dist/acorn.js:1747
  throw err;
  ^

SyntaxError: Unexpected token (49:30)
    at Parser.pp.raise (/usr/local/lib/node_modules/auto-install/node_modules/acorn/dist/acorn.js:1745:13)
    at Parser.pp.unexpected (/usr/local/lib/node_modules/auto-install/node_modules/acorn/dist/acorn.js:2264:8)
    at Parser.pp.expect (/usr/local/lib/node_modules/auto-install/node_modules/acorn/dist/acorn.js:2258:26)
    at Parser.pp.parseObj (/usr/local/lib/node_modules/auto-install/node_modules/acorn/dist/acorn.js:1293:12)
    at Parser.pp.parseExprAtom (/usr/local/lib/node_modules/auto-install/node_modules/acorn/dist/acorn.js:1124:19)
    at Parser.pp.parseExprSubscripts (/usr/local/lib/node_modules/auto-install/node_modules/acorn/dist/acorn.js:1023:19)
    at Parser.pp.parseMaybeUnary (/usr/local/lib/node_modules/auto-install/node_modules/acorn/dist/acorn.js:1004:19)
    at Parser.pp.parseExprOps (/usr/local/lib/node_modules/auto-install/node_modules/acorn/dist/acorn.js:948:19)
    at Parser.pp.parseMaybeConditional (/usr/local/lib/node_modules/auto-install/node_modules/acorn/dist/acorn.js:930:19)
    at Parser.pp.parseMaybeAssign (/usr/local/lib/node_modules/auto-install/node_modules/acorn/dist/acorn.js:908:19)
```

**Comment by zeg-io** [comment]
My thoughts: I use WebStorm, which auto-saves files from time to time.  Maybe some partially written code triggered the failure?

**Comment by siddharthkp** [comment]
@zeg-io Yes, that seems like a possible reason.

I have experienced this once before, the parsing breaks when trying to find `require` statements. Something that can be fixed though. 

Adding `bug` label.

**Comment by siddharthkp** [comment]
Fixed in https://github.com/siddharthkp/auto-install/commit/662a266c8350ce3b6e3a7dca1cc60f02aa4a1fce
